bindAddress: :5353
primaryDNS:
  - name: Domestic
    address: 127.0.0.1:4053
    protocol: udp
    socks5Address:
    timeout: 4
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
alternativeDNS:
  - name: Foreign
    address: 127.0.0.1:6053
    protocol: udp
    socks5Address:
    timeout: 8
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: false
whenPrimaryDNSAnswerNoneUse: alternativeDNS
ipNetworkFile:
  primary: /etc/cleardns/list/china_ip_list.txt
  alternative: /etc/overture/loopback.txt
domainFile:
  primary: /etc/cleardns/list/chinalist.txt
  alternative: /etc/cleardns/list/gfwlist.txt
  matcher: suffix-tree
hostsFile:
  hostsFile: /etc/overture/hosts
  finder: full-map
