bindAddress: :5353
dohEnabled: false
primaryDNS:
  - name: Domestic
    address: 127.0.0.1:4053
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
alternativeDNS:
  - name: Foreign
    address: 127.0.0.1:6053
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: true
whenPrimaryDNSAnswerNoneUse: alternativeDNS
ipNetworkFile:
  primary: /etc/cleardns/asset/china-ip.txt
  alternative: /dev/null
domainFile:
  primary: /etc/cleardns/asset/chinalist.txt
  alternative: /etc/cleardns/asset/gfwlist.txt
  matcher: suffix-tree
hostsFile:
  hostsFile: /etc/hosts
  finder: full-map
cacheSize: 4096
